config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'session/new'
  get 'users/new'
  get 'static_pages/home'
  get '/about', to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  # post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :selections
  end

  resources :stations


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/station.rb
class Station < ApplicationRecord

  has_many :selections, dependent: :delete_all
  has_many :users, :through => :selections

  validates :code, presence: true
  attr_reader :admin_user

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  attr_accessor :stations
  before_action :admin_user, only: [:index, :show, :new, :edit, :update, :destroy]

  def index
    @stations = Station.all
  end

  def show
    @station = Station.find(params[:id])
  end

  def new
    @station = Station.new
  end

  def edit
    @station = Station.find(params[:id])
  end

  def create
    respond_to do |format|
      @station = Station.new(station_params)
      puts @station.inspect
      if @station.save
        format.html {
          redirect_to @station,
          notice: 'Station was successfully created.'
        }
        format.json {
          render :show,
          status: :created,
          location: @station
        }
      else
        format.html { render  :new }
        format.json {
          render  json: @station.errors,
                status: :unprocessable_entity
        }
      end
    end
  end

  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station,
                      notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render  :edit }
        format.json { render  json: @station.errors,
                              status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Station.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to stations_url,
                    notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def station_params
    params.require(:station).permit(:code, :description)
  end

  def admin_user
    redirect_to(root_url) unless :admin_user # current_user.admin?
  end

end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_errors.html.erb
<% if station.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

    <ul>
    <% station.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/stations/_form.html.erb
<%= form_with(model: station, local: true ) do |form| %>
<% if station.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

    <ul>
    <% station.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class='col-md-6 col-md-offset-3 form-inline '>
    <div class="form-group">
      <%= form.label :code %>
      <%= form.text_field :code %>
    </div>

    <div class="form-group form-inline">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>
  </div>

    <%= form.submit class: 'btn btn-primary btn-sm' %>

<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <!-- col-md-4   table-responsive-md -->
    <table class='table table-hover'>
      <thead>
        <tr scope='row'>
          <th scope='col'>Code</th>
          <th scope='col'>Location name</th>
        </tr>
      </thead>
      <tbody>
        <% @stations.each do |station| %>
          <tr scope='row'>
            <td><%= link_to station.code, station_path(station) %></td>
            <td><%= station.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Add New Station", new_station_path, {class: 'btn btn-primary btn-block'} %>
  </div>

</div>

app/views/stations/new.html.erb
<h1>Add New Station</h1>


<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @station.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @station.description %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %> |
<%= link_to 'Delete', station_path, {method: :delete} %>