config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'session/new'
  get 'users/new'
  get 'static_pages/home'
  get '/about', to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  # post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :selections
  end

  resources :stations


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :user
  belongs_to :station
end

app/models/user.rb
class User < ApplicationRecord

  has_many :selections
  has_many :stations, :through => :selections
  accepts_nested_attributes_for :selections, reject_if: :all_blank, allow_destroy: true

  attr_accessor :forecast, :logged_in_user

  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  include SelectionsHelper
  include SessionsHelper
  def index
    @selections = current_user.stations # current_user.stations # provides an array of station objects
    @forecasts = get_forecast(current_user.stations) # @selections
    @stations = Station.all
    @unselected_stations = @stations - @selections
    @user = current_user
  end

  def show
  end

  def new
    @selection = Selection.new
  end

  def create
     Selection.find_or_create_by(user_id: current_user.id,
                              station_id: params[:id])
     redirect_to user_selections_path
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params)
    # if @user.update_attributes(user_params)
    #   flash[:success] = 'Info updated.'
      redirect_to @selection
    else
      render 'user#show'
    end
  end

  def destroy
   Selection.find_by(user_id: current_user.id,
                  station_id: params[:id]).destroy
   redirect_to user_selections_path
  end

end

app/helpers/selections_helper.rb
require 'json'
require 'ostruct'

module SelectionsHelper
  def get_forecast(selections)
    w_api = Wunderground.new(ENV['WUNDERGROUND_API_KEY'])

    selections.map do |selection|
      raw_response = w_api.forecast_and_conditions_for("pws:#{selection.code}")
      response = JSON.parse(raw_response.to_json, object_class: OpenStruct)
      forecast = {
        :station_id => selection.id,
        :description => selection.description,
        :elevation =>
          response.current_observation.observation_location.elevation,
        :observations => {
          :time => response.current_observation.observation_time_rfc822[0..-6],
          :temp => response.current_observation.temp_f,
          :wind => response.current_observation.wind_string,
          :precip_today => [response.current_observation.precip_today_in.to_f, 0].max,
          :precip_1hr => [response.current_observation.precip_1hr_in.to_f, 0].max,
          :icon_url => response.current_observation.icon_url
        }
      }

      daily_forecasts = response.forecast.simpleforecast.forecastday
      forecast[:daily_fx] = daily_forecasts.map do |fx|
        {
          :day => fx.date.weekday_short,
          :pop => fx.pop,
          :qpf => fx.qpf_allday.in,
          :snow_in => fx.snow_allday.in,
          :max_wind_mph => fx.maxwind.mph
        }
      end
      forecast
    end
  end
end

app/views/selections/_stationList-checkbox.html.erb
<div class='stnCheckbox'>
  <div class='form-group checkbox'>
    <%= form_for(@user) do |f| %>
      <% Station.all.each do |station| %>
        <div>
          <%= check_box_tag :station_ids, station.id, @user.stations.include?(station), :name => 'user[station_ids][]' %>
          <%= label_tag :station_ids, station.description %>
        </div>
      <% end %>
      <%= submit_tag %>
    <% end %>
  </div>
</div>

app/views/selections/_stationList-checkbox2.html.erb
<div class='stnCheckbox'>
  <div class='form-group checkbox '>
    <%= form_for(@user) do |f| %>
      <% @stations.each do |station| %>
        <div class='checkbox'>
          <%= check_box_tag "user[station_ids][]", station.id, f.object.stations.include?(station), class: 'input checkbox' %>
          <%= station.description %>
        </div>
      <% end %>
    <%= submit_tag %>
    <% end %>
  </div>
</div>


<!--  collection_check_boxes -->
<!-- collection_check_boxes (station selection_ids, Station.all, :id, station.id) -->




<!-- check_box_tag "user[station_ids][]", station.id, f.object.stations.include?(station) -->
 <!-- f.submit " Choose ", class: "btn btn-primary" -->

<!-- check_box_tag :station_ids, station.id, @user.stations.include?(station), :name => 'user[station_ids][]'  -->

app/views/selections/_stationList.html.erb
 <div class="btn-group-vertical ">  <!--buttonNav-->
  <% @unselected_stations.each do |unselected_station| %>
    <div>
        <%= button_to(unselected_station.description,
          user_selections_path(id: unselected_station.id),
          {class: 'btn btn-primary btn-sm btn-block'}) %>
    </div>
  <% end %>
</div>

app/views/selections/_weatherDisplay.html.erb
  <% @forecasts.each do |fcast| %>
    <% if fcast %>
      <!-- <div class='row'> -->
          <div class='forecastBox'>
            <div class='title'>
              <div class='item '>
                <%= fcast[:description] %>
              </div>
              <div class='item'>
                <%= fcast[:elevation] %>
              </div>
              <div class='item'>
                <%= fcast[:observations][:temp] %>°F
              </div>
            </div>
              <!-- <div><%= link_to('Remove',
                user_selection_path(:id => fcast[:station_id]), {method: :delete, class: 'btn btn-default btnRemove'}) %></div> -->

            <div class='forecastTable '> <!-- pull-right table-responsive -->
              <div class='item'>Precip: (1hr | 24hrs): <%= fcast[:observations][:precip_1hr] %>&nbsp;|&nbsp;<%= fcast[:observations][:precip_today] %></div>
              <div class='item center'><%= image_tag fcast[:observations][:icon_url], class: 'image-responsive' %></div>
              <table class='table table-condensed text-right forecastTable borderless'>
                <thead>
                  <tr scope='row'>
                    <th></th>
                    <th class='text-right'><%= fcast[:daily_fx][0][:day] %></th>
                    <th class='text-right'><%= fcast[:daily_fx][1][:day] %></th>
                    <th class='text-right'><%= fcast[:daily_fx][2][:day] %></th>
                    <th class='text-right'><%= fcast[:daily_fx][3][:day] %></th>
                  </tr>
                </thead>
                <tbody>
                  <tr scope='row'>
                    <th><i class='wi wi-humidity icon-humidity' title='Probably of Precipitation' ></i></th> <!--POP -->
                    <td><%= fcast[:daily_fx][0][:pop] %></td>
                    <td><%= fcast[:daily_fx][1][:pop] %></td>
                    <td><%= fcast[:daily_fx][2][:pop] %></td>
                    <td><%= fcast[:daily_fx][3][:pop] %></td>
                  </tr>
                  <tr scope='row'>
                    <th><i class='fas fa-tint' title='Forecasted Precipitation'></i></th> <!--QPF wi wi-raindrop icon-->
                    <td><%= fcast[:daily_fx][0][:qpf] %></td>
                    <td><%= fcast[:daily_fx][1][:qpf] %></td>
                    <td><%= fcast[:daily_fx][2][:qpf] %></td>
                    <td><%= fcast[:daily_fx][3][:qpf] %></td>
                  </tr>
                  <tr scope='row'>
                    <th><i class='fas fa-snowflake icon-snow' title='Forecasted Snow'></i></th> <!--SNOW -->
                    <td><%= fcast[:daily_fx][0][:snow_in] %></td>
                    <td><%= fcast[:daily_fx][1][:snow_in] %></td>
                    <td><%= fcast[:daily_fx][2][:snow_in] %></td>
                    <td><%= fcast[:daily_fx][3][:snow_in] %></td>
                  </tr>
                  <tr scope='row'>
                    <th><i class='wi wi-strong-wind icon' title='Forecasted Max Winds'></i></th> <!--WIND -->
                    <td><%= fcast[:daily_fx][0][:max_wind_mph] %></td>
                    <td><%= fcast[:daily_fx][1][:max_wind_mph] %></td>
                    <td><%= fcast[:daily_fx][2][:max_wind_mph] %></td>
                    <td><%= fcast[:daily_fx][3][:max_wind_mph] %></td>
                  </tr>
                <!-- <% fcast[:daily_fx].each do |daily_fx| %>
                  <tr>
                    <th><%= daily_fx[:day] %></th>
                    <td><%= daily_fx[:pop] %></td>
                    <td><%= daily_fx[:qpf] %></td>
                    <td><%= daily_fx[:snow_in] %></td>
                    <td><%= daily_fx[:max_wind_mph] %></td>
                  </tr>
                <% end %> -->
              </tbody>
            </table>
          </div>
          <div class='updateTime'>
            <%= fcast[:observations][:time]%>
          </div>
        </div>

      <!-- </div> -->
      <!-- </div> -->
    <% end %>
  <% end %>

<!-- </div> -->

app/views/selections/index.html.erb
<p id="notice"><%= notice %></p>

<div class='row selectionContainer'>

  <% if @forecasts %>
    <div class='col-sm-12'>
      <h1>Dashboard</h1>
      <div class='col-sm-3'>
      </div>
      <div class='col-sm-6 ForecastContainer'>
        <center><button type="button" class="btn btn-primary btn-md center" data-toggle="modal" data-target="#stationModal">
          Change Stations
        </button></center>
        <%= render 'weatherDisplay' %>
      </div>
      <div class='col-sm-3'>
      </div>
    </div>
  <% end %>

</div>

<!-- Station Modal -->
<div class="modal fade" id="stationModal" tabindex="-1" role="dialog" aria-labelledby="Station Selection">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_for(@user) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="Station Selection">Change Stations</h4>
        </div>
        <div class="modal-body">
          <div class='stnCheckbox'>
            <div class='form-group checkbox'>
                <% Station.all.each do |station| %>
                  <div>
                    <%= check_box_tag :station_ids, station.id, @user.stations.include?(station), :name => 'user[station_ids][]' %>
                    <%= label_tag :station_ids, station.description %>
                  </div>
                <% end %>

            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag "Update", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>