config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'session/new'
  get 'users/new'
  get 'static_pages/home'
  get '/about', to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  # post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    resources :selections
  end

  resources :stations


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin.html.erb
<div class='row'>
  <nav class='navbar navbar-default col-sm-6 col-sm-offset-2' role='navigation'>
        <ul class='nav navbar-nav center'>
           <li><%= link_to "Manage Stations", stations_path %></li>
           <li><%= link_to "Manage Users", users_path %></li>
        </ul>
  </nav>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div> <!-- <div class='navbar-header'> -->
      <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#myNavbar'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to "powfinder", root_path, id: "logo" %>
      <div class='collapse navbar-collapse' id='myNavbar'>
        <ul class='nav navbar-nav pull-right'>
          <li></li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if logged_in? %>
            <li class='dropdown'>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role='button'>
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", current_user %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>Railspowfinder</title>
    <meta charset='utm-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <%= favicon_link_tag asset_path('icon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class='container'>
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
  <script defer src="https://use.fontawesome.com/releases/v5.0.12/js/all.js" integrity="sha384-Voup2lBiiyZYkRto2XWqbzxHXwzcm4A5RfdfG6466bu5LqjwwrjXCMBQBLMWh7qR" crossorigin="anonymous"></script>
</html>



<!-- FIXME:  why can't I
if current_user.admin?
render 'layouts/admin'
<% end

 -->